; PlatformIO Project Configuration
; Jasiu Pong - ESP32 Two-Player Pong Game

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
    mathieucarbou/ESP Async WebServer@^3.0.6
    mathieucarbou/AsyncTCP@^3.1.4
    bblanchon/ArduinoJson@^7.0.0
lib_ignore =
    ESPAsyncTCP-esphome
    AsyncTCP_RP2040W

extra_scripts = pre:scripts/build_web.py
